packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.5
  '@orpc/client': ^1.11.2
  '@orpc/openapi': ^1.11.2
  '@orpc/server': ^1.11.2
  '@orpc/zod': ^1.11.2
  prisma: ^7.0.0
  '@prisma/client': ^7.0.0
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@types/node': ^22.19.1
  better-auth: ^1.3.34
  dotenv: ^17.2.3
  lucide-react: ^0.553.0
  next: ^16.0.3
  react: 19.2.0
  react-dom: 19.2.0
  tsdown: ^0.16.4
  tsx: ^4.20.6
  turbo: ^2.6.1
  zod: 4.1.12
  typescript: ^5.9.3
  nanoid: ^5.1.6
  '@orpc/tanstack-query': ^1.11.2
  '@tanstack/react-form': ^1.25.0
  '@tanstack/react-query': ^5.90.9
  '@tanstack/react-query-devtools': ^5.90.2
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  tailwindcss: ^4.1.17
  babel-plugin-react-compiler: 19.1.0-rc.3
  sonner: 2.0.7
  tw-animate-css: ^1.4.0
  '@tailwindcss/postcss': ^4.1.17

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
