packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.2.0
  '@orpc/client': ^1.10.0
  '@orpc/openapi': ^1.10.0
  '@orpc/server': ^1.10.0
  '@orpc/zod': ^1.10.0
  '@polar-sh/better-auth': ^1.1.3
  '@prisma/client': ^6.15.0
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@types/node': ^22.13.11
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  next: 16.0.0
  tsdown: ^0.15.5
  turbo: ^2.5.4
  zod: 4.1.12

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
